### ISSUE TITLE
Invalid notification about array in array changes

### ISSUE THREAD

**Issue by miyconst** [Palindrom/palindrom-polymer-client#14] opened 2016-05-12 09:19 UTC
- Checkout https://github.com/miyconst/Playground/.
- Open http://localhost:8080/playground.
- Play with the Matrix control by pressing `++` and `--` buttons.

The `--` button seems to work correct, but after `++` the matrix cells lack values.

![image](https://cloud.githubusercontent.com/assets/6435556/15209748/371fa1e8-1833-11e6-9a9f-4f55482b4100.png)

![image](https://cloud.githubusercontent.com/assets/6435556/15209758/4128117a-1833-11e6-8c5f-91d15314b62e.png)

![image](https://cloud.githubusercontent.com/assets/6435556/15209767/4c27dd44-1833-11e6-9543-3572b256ae55.png)

cc @warpech, @tomalec

**Comment by warpech** [comment] 2016-05-24 09:02
Snapshot JSON and JSON-Patch here: https://gist.github.com/warpech/9c43d798a3b7f90f2fbf8be7945075d8

I think this is exactly the problem of the test: https://github.com/PuppetJs/puppet-polymer-client/blob/c59a9e1932401efafe33e14b30ca71f8a1be9bd4/test/d-b-n_smoke/arrays.html#L158-L172

Which is a Polymer issue: https://github.com/Polymer/polymer/issues/3377

@joozek78 will change this test to pass, so that it will be GREEN with this incorrect behavior and RED when Polymer fixes the problem.

**Comment by joozek78** [comment] 2016-05-24 09:21
Marking as duplicate, as #17 tracks root cause for this problem. Please continue any discussion there.

**Comment by tomalec** [comment] 2016-05-29 16:15
It seems it's not (just) this issue, as I have updated te tests, and use-case for Polymer thing and everything works fine, but OP is still a problem.

**Comment by tomalec** [comment] 2016-05-29 17:34
Here is Polymer bug-case http://jsbin.com/bimipe/edit?html,console,output so it's about "applying on array of primitives consecutive `splice`s with overlapping values"

**Comment by tomalec** [comment] 2016-05-29 18:15
Here is new Polymer issue for it https://github.com/Polymer/polymer/issues/3682
It seems to be quite narrow case, and buried deep in Polymer's template binding.

I do not see any workaround form `puppet-polymer-client` that makes sense.

The ways to go I see:
1. Make a note on README about this issue, and wait for Polymer team to fix that,

  Some thing like
  > Arrays of primitives seems to make problems for Polymer template binding (see #issues), we only can advice you to avoid them.
2. Mark it as somehow "expected behavior" and write test for it, that will make sure that `puppet-polymer-client` causes a bug like OP,
3. Try to fix Polymer.

**Comment by miyconst** [comment] 2016-05-30 06:39
I vote for the option 1 and against the option 3. We have other more important tasks for your valuable time.

**Comment by tomalec** [comment] 2016-05-30 08:44
@warpech, @joozek78  WDYT?

**Comment by joozek78** [comment] 2016-05-30 09:48
I vote for option 2 (as I have in past for similar cases). Here's why:

1. Tests help us assert current state of our system and this behavior is part of our current state, whether we want it or not.
1. Right now we can tell our clients "this is broken in such-and-such way" (maybe this breakage doesn't affect their use case). If we won't write tests for this we will never know if it is still broken in such-and-such way (maybe it'll start throwing exceptions and we won't notice)
1. If this is fixed our test will detect it and we'll respond with happy cheering and bug closing. It may be that polymer will fix it inadvertently and won't ever close their bug. *How do you propose we detect that?*
1. This test looks like it's dead-easy to implement, so no substantial cost on our side

Of course, I also think we should do 1. and shouldn't be doing 3.

**Comment by warpech** [comment] 2016-05-30 09:48
I vote for option 1.

I am against tests that fail on purpose. So if we have a test for that, let's comment out the test and do the option 2 as wel.

**Comment by tomalec** [comment] 2016-05-30 13:19
1., 2., done
http://puppetjs.github.io/puppet-polymer-client/test/?grep=non-desired-but-expected%2Fdue-to-polymer-bugs%5C.html
https://github.com/PuppetJs/puppet-polymer-client#template-binding-issues

**Comment by joozek78** [comment] 2016-05-30 13:48
"not desired but expected" is a cool name. We should use it in all such cases

**Comment by tomalec** [comment] 2016-09-26 13:38
We need to see what Polymer 2.x bring fot that https://github.com/Starcounter/CompanyTrack/issues/233

**Comment by alshakero** [comment] 2017-08-29 12:28
This is fixed in Polymer 2.0 💃

**Comment by warpech** [comment] 2017-09-26 20:49
@alshakero Did you need to revert some tests that checked if this is failing in Polymer 1.x?

**Comment by alshakero** [comment] 2017-09-27 10:46
Sorry, I don't fully understand the question. Here are all the relevant facts:

1- We have a test that actually expects the undesired failure. And it is still passing, and this means this bug is still there in Polymer 1.x.

This test didn't pass in Polymer 2.x and I changed the spec to test for the desired behaviour. And it is passing. Which means it is fixed in Polymer 2.x.

**Comment by warpech** [comment] 2017-09-27 22:15
Great! So this means that we can close this as fixed in Polymer 2.0-version as it is merged to `master` of this repo.

@miyconst please reopen if you'd like to wait until this can be proven in a Starcounter app.

**Closed by warpech** 2017-09-27 22:15 UTC
Labels: blocked, bug
